#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
HTTP_PROXY=localhost:8123
GFWLIST_URL=https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt

curl -s $GFWLIST_URL | base64 -d

echo
echo "!----------------- HH CUSTOM RULES -----------------"
for file in `ls ${DIR}/custom.list.d` ; do
  echo
  cat ${DIR}/custom.list.d/$file
done
